# Generated by Django 5.2.5 on 2025-12-04 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0010_alter_appointment_id_no_alter_appointment_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='id_no',
        ),
    ]
